Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.
Tạo một đối tượng NumPy ndarray
NumPy được sử dụng để làm việc với mảng. Đối tượng mảng trong NumPy được gọi là ndarray.
Chúng ta có thể tạo một ndarrayđối tượng NumPy bằng cách sử dụng array()hàm.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.
type(): Hàm Python tích hợp này cho chúng ta biết loại đối tượng được truyền cho nó. Giống như đoạn mã trên, nó hiển thị đó arr là numpy.ndarray loại.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:
Để tạo một ndarray, chúng ta có thể chuyển một danh sách, bộ dữ liệu hoặc bất kỳ đối tượng giống mảng nào vào phương array() thức và nó sẽ được chuyển đổi thành ndarray:

In [2]:
# Use a tuple to create a NumPy array:
# Sử dụng bộ dữ liệu để tạo mảng NumPy:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).
nested array: are arrays that have arrays as their elements.
Kích thước trong mảng
Thứ nguyên trong mảng là một mức độ sâu của mảng (mảng lồng nhau).
mảng lồng nhau: là các mảng có mảng là các phần tử của chúng.

0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
Mảng 0-D
Mảng 0-D hoặc Vô hướng là các phần tử trong một mảng. Mỗi giá trị trong một mảng là một mảng 0-D.

In [3]:
# Create a 0-D array with value 42
# Tạo mảng 0-D có giá trị 42
import numpy as np

arr = np.array(42)

print(arr)

42


1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.
Mảng 1-D
Mảng có các phần tử là mảng 0-D được gọi là mảng một chiều hoặc mảng 1-D.
Đây là những mảng phổ biến và cơ bản nhất.

In [4]:
# Create a 1-D array containing the values 1,2,3,4,5:
# Tạo mảng 1-D chứa các giá trị 1,2,3,4,5:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.
NumPy has a whole sub module dedicated towards matrix operations called numpy.mat
Mảng 2-D
Mảng có các phần tử là mảng 1-D được gọi là mảng 2-D.
Chúng thường được sử dụng để biểu diễn các tensor ma trận hoặc bậc 2.
NumPy có toàn bộ mô-đun phụ dành riêng cho các hoạt động ma trận được gọi là numpy.mat

In [5]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
# Tạo mảng 2-D chứa hai mảng có giá trị 1,2,3 và 4,5,6:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.
These are often used to represent a 3rd order tensor.
Mảng 3-D
Một mảng có các mảng 2-D (ma trận) làm phần tử của nó được gọi là mảng 3-D.
Chúng thường được sử dụng để biểu diễn tensor bậc 3.

In [6]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
# Tạo một mảng 3-D có hai mảng 2-D, cả hai đều chứa hai mảng có giá trị 1,2,3 và 4,5,6:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
Kiểm tra số lượng kích thước?
NumPy Arrays cung cấp ndim thuộc tính trả về một số nguyên cho chúng ta biết mảng đó có bao nhiêu chiều.

In [7]:
# Check how many dimensions the arrays have:
# Kiểm tra xem mảng có bao nhiêu chiều:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.
Mảng chiều cao hơn
Một mảng có thể có số chiều bất kỳ.
Khi mảng được tạo, bạn có thể xác định số chiều bằng cách sử dụng ndmin đối số.

In [8]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
# Tạo một mảng có 5 chiều và xác minh rằng nó có 5 chiều:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.
Trong mảng này chiều trong cùng (điểm mờ thứ 5) có 4 phần tử, điểm mờ thứ 4 có 1 phần tử là vectơ, chiều mờ thứ 3 có 1 phần tử là ma trận với vectơ, điểm mờ thứ 2 có 1 phần tử là mảng 3D và Dim thứ nhất có 1 phần tử là mảng 4D.