Access Array Elements
Array indexing is the same as accessing an array element.
You can access an array element by referring to its index number.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
Truy cập các phần tử mảng
Lập chỉ mục mảng cũng giống như truy cập một phần tử mảng.
Bạn có thể truy cập một phần tử mảng bằng cách tham khảo số chỉ mục của nó.
Các chỉ mục trong mảng NumPy bắt đầu bằng 0, nghĩa là phần tử đầu tiên có chỉ mục 0 và phần tử thứ hai có chỉ mục 1, v.v.

In [1]:
# Get the first element from the following array:
# Lấy phần tử đầu tiên từ mảng sau:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [2]:
# Get the second element from the following array.
# Lấy phần tử thứ hai từ mảng sau.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [3]:
# Get third and fourth elements from the following array and add them.
#Lấy phần tử thứ ba và thứ tư từ mảng sau và thêm chúng.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.
Truy cập mảng 2-D
Để truy cập các phần tử từ mảng 2-D, chúng ta có thể sử dụng các số nguyên được phân tách bằng dấu phẩy biểu thị thứ nguyên và chỉ mục của phần tử.
Hãy nghĩ về mảng 2-D giống như một bảng có hàng và cột, trong đó thứ nguyên đại diện cho hàng và chỉ mục đại diện cho cột.

In [4]:
# Access the element on the first row, second column:
# Truy cập phần tử ở hàng đầu tiên, cột thứ hai:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2


In [6]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('3th element on 2rd row: ', arr[1, 2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3th element on 2rd row:  8


In [7]:
# Access the element on the 2nd row, 5th column:
# Truy cập phần tử ở hàng thứ 2, cột thứ 5:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.
Truy cập mảng 3-D
Để truy cập các phần tử từ mảng 3-D, chúng ta có thể sử dụng các số nguyên được phân tách bằng dấu phẩy biểu thị kích thước và chỉ mục của phần tử.

In [10]:
# Access the third element of the second array of the first array:
# Truy cập phần tử thứ ba của mảng thứ hai của mảng đầu tiên:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

Ví dụ giải thích
arr[0, 1, 2]in giá trị 6.

Và đây là lý do tại sao:

Số đầu tiên đại diện cho chiều thứ nhất, chứa hai mảng:
[[1, 2, 3], [4, 5, 6]]
và:
[[7, 8, 9], [10, 11, 12]]
Vì chúng tôi đã chọn 0, chúng tôi còn lại mảng đầu tiên:
[[1, 2, 3], [4, 5, 6]]

Số thứ hai đại diện cho chiều thứ hai, cũng chứa hai mảng:
[1, 2, 3]
và:
[4, 5, 6]
Vì chúng tôi đã chọn 1, nên chúng tôi chỉ còn lại mảng thứ hai:
[4, 5, 6]

Số thứ ba đại diện cho chiều thứ ba, chứa ba giá trị:
4
5
6
Vì chúng tôi đã chọn 2, nên chúng tôi có giá trị thứ ba:
6

Negative Indexing
Use negative indexing to access an array from the end.
Lập chỉ mục tiêu cực
Sử dụng lập chỉ mục phủ định để truy cập một mảng từ cuối.

In [9]:
# Print the last element from the 2nd dim:
# In phần tử cuối cùng từ mờ thứ 2:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
