Slicing arrays
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1
Cắt mảng
Cắt trong python có nghĩa là lấy các phần tử từ một chỉ mục đã cho này sang một chỉ mục đã cho khác.
Chúng tôi chuyển lát thay vì chỉ mục như thế này: .[start:end]
Chúng ta cũng có thể xác định bước này như sau: .[start:end:step]
Nếu chúng tôi không vượt qua bắt đầu thì nó được coi là 0
Nếu chúng ta không vượt qua end thì độ dài của mảng được xem xét theo chiều đó
Nếu chúng tôi không vượt qua bước thì nó được coi là 1

In [1]:
# Slice elements from index 1 to index 5 from the following array:
# Cắt các phần tử từ chỉ mục 1 đến chỉ mục 5 từ mảng sau:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


Note: The result includes the start index, but excludes the end index.
Lưu ý: Kết quả bao gồm chỉ mục bắt đầu nhưng không bao gồm chỉ mục kết thúc.

In [2]:
# Slice elements from index 4 to the end of the array:
# Cắt các phần tử từ chỉ số 4 đến cuối mảng:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [3]:
# Slice elements from the beginning to index 4 (not included):
# Cắt các phần tử từ đầu đến chỉ số 4 (không bao gồm):
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


Negative Slicing
Use the minus operator to refer to an index from the end:
Cắt âm
Sử dụng toán tử trừ để tham chiếu chỉ mục từ cuối:

In [4]:
# Slice from the index 3 from the end to index 1 from the end:
# Cắt từ chỉ số 3 từ đầu đến chỉ số 1 từ cuối:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


STEP
Use the step value to determine the step of the slicing
BƯỚC CHÂN
Sử dụng step giá trị để xác định bước cắt

In [5]:
# Return every other element from index 1 to index 5:
# Trả về mọi phần tử khác từ chỉ mục 1 đến chỉ mục 5:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [6]:
# Return every other element from the entire array:
# Trả về mọi phần tử khác từ toàn bộ mảng:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


Slicing 2-D Arrays
Cắt mảng 2-D

In [7]:
# From the second element, slice elements from index 1 to index 4 (not included):
# Từ phần tử thứ hai, cắt các phần tử từ chỉ mục 1 đến chỉ mục 4 (không bao gồm):
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


Note: Remember that second element has index 1.
Lưu ý: Hãy nhớ rằng phần tử thứ hai có chỉ số 1.

In [8]:
# From both elements, return index 2:
# Từ cả hai phần tử, trả về chỉ số 2:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [9]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
# Từ cả hai phần tử, cắt chỉ mục 1 đến chỉ mục 4 (không bao gồm), điều này sẽ trả về một mảng 2-D:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
