Data Types in Python
By default Python have these data types:
strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
Các kiểu dữ liệu trong Python
Theo mặc định Python có các kiểu dữ liệu sau:
strings- dùng để thể hiện dữ liệu văn bản, văn bản được đưa ra dưới dấu ngoặc kép. ví dụ: "ABCD"
integer- Dùng để biểu diễn số nguyên. ví dụ -1, -2, -3
float- Dùng để biểu diễn số thực. ví dụ 1,2, 42,42
boolean- Dùng để biểu thị Đúng hoặc Sai.
complex- Dùng để biểu diễn số phức. ví dụ: 1,0 + 2,0j, 1,5 + 2,5j

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
Các kiểu dữ liệu trong NumPy
NumPy có một số kiểu dữ liệu bổ sung và đề cập đến các kiểu dữ liệu có một ký tự, như iđối với số nguyên, uđối với số nguyên không dấu, v.v.
Dưới đây là danh sách tất cả các loại dữ liệu trong NumPy và các ký tự được sử dụng để biểu thị chúng.

i- số nguyên
b- boolean
u- số nguyên không dấu
f- trôi nổi
c- phao phức hợp
m- đồng bằng thời gian
M- ngày giờ
O- sự vật
S- sợi dây
U- chuỗi unicode
V- đoạn bộ nhớ cố định cho loại khác ( void )

Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:
Kiểm tra kiểu dữ liệu của một mảng
Đối tượng mảng NumPy có một thuộc tính được gọi dtype là trả về kiểu dữ liệu của mảng:

In [1]:
# Get the data type of an array object:
# Lấy kiểu dữ liệu của một đối tượng mảng:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [2]:
# Get the data type of an array containing strings:
# Lấy kiểu dữ liệu của một mảng chứa chuỗi:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements
Tạo mảng với kiểu dữ liệu được xác định
Chúng ta sử dụng hàm array() để tạo mảng, hàm này có thể nhận một đối số tùy chọn: dtype cho phép chúng ta xác định kiểu dữ liệu dự kiến ​​của các thành phần mảng

In [3]:
# Create an array with data type string:
# Tạo một mảng với chuỗi kiểu dữ liệu:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


For i, u, f, S and U we can define size as well
Đối với i, u, f, S và U chúng ta cũng có thể xác định kích thước

In [4]:
# Create an array with data type 4 bytes integer:
# Tạo một mảng có kiểu dữ liệu số nguyên 4 byte:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.
ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.
Điều gì xảy ra nếu một giá trị không thể được chuyển đổi?
Nếu một loại được đưa ra trong đó các phần tử không thể được truyền thì NumPy sẽ đưa ra ValueError.
ValueError: Trong Python ValueError được nâng lên khi loại đối số được truyền cho hàm không mong muốn/không chính xác.

In [6]:
# A non integer string like 'a' can not be converted to integer (will raise an error):
# Không thể chuyển đổi chuỗi không nguyên như 'a' thành số nguyên (sẽ gây ra lỗi):
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.
Chuyển đổi kiểu dữ liệu trên mảng hiện có
Cách tốt nhất để thay đổi kiểu dữ liệu của một mảng hiện có là tạo một bản sao của mảng bằng phương thức astype().
Hàm astype() tạo một bản sao của mảng và cho phép bạn chỉ định kiểu dữ liệu làm tham số.
Kiểu dữ liệu có thể được chỉ định bằng cách sử dụng một chuỗi, như 'f' cho float, 'i' cho số nguyên, v.v. hoặc bạn có thể sử dụng kiểu dữ liệu trực tiếp như float cho float và int cho số nguyên.

In [7]:
# Change data type from float to integer by using 'i' as parameter value:
# Thay đổi kiểu dữ liệu từ float sang số nguyên bằng cách sử dụng 'i' làm giá trị tham số:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
# Change data type from float to integer by using int as parameter value:
# Thay đổi kiểu dữ liệu từ float sang số nguyên bằng cách sử dụng int làm giá trị tham số:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [9]:
# Change data type from integer to boolean:
# Thay đổi kiểu dữ liệu từ số nguyên sang boolean:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
