The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
Sự khác biệt giữa Sao chép và Xem
Sự khác biệt chính giữa bản sao và chế độ xem của một mảng là bản sao là một mảng mới và chế độ xem chỉ là chế độ xem của mảng ban đầu.
Bản sao sở hữu dữ liệu và mọi thay đổi được thực hiện đối với bản sao sẽ không ảnh hưởng đến mảng ban đầu và mọi thay đổi được thực hiện đối với mảng ban đầu sẽ không ảnh hưởng đến bản sao.
Chế độ xem không sở hữu dữ liệu và mọi thay đổi được thực hiện đối với chế độ xem sẽ ảnh hưởng đến mảng ban đầu và mọi thay đổi được thực hiện đối với mảng ban đầu sẽ ảnh hưởng đến chế độ xem.

Copy
Sao chép

In [1]:
# Make a copy, change the original array, and display both arrays:
# Tạo một bản sao, thay đổi mảng ban đầu và hiển thị cả hai mảng:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


The copy SHOULD NOT be affected by the changes made to the original array.
Bản sao KHÔNG NÊN bị ảnh hưởng bởi những thay đổi được thực hiện đối với mảng ban đầu.

View
Xem

In [2]:
# Make a view, change the original array, and display both arrays:
# Tạo chế độ xem, thay đổi mảng ban đầu và hiển thị cả hai mảng:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


The view SHOULD be affected by the changes made to the original array.
Chế độ xem NÊN bị ảnh hưởng bởi những thay đổi được thực hiện đối với mảng ban đầu.

Make Changes in the VIEW:
Thực hiện các thay đổi trong VIEW:

In [3]:
# Make a view, change the view, and display both arrays:
# Tạo chế độ xem, thay đổi chế độ xem và hiển thị cả hai mảng:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


The original array SHOULD be affected by the changes made to the view.
Mảng ban đầu NÊN bị ảnh hưởng bởi những thay đổi được thực hiện đối với chế độ xem.

Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base attribute refers to the original object.
Kiểm tra xem mảng có sở hữu dữ liệu của nó không
Như đã đề cập ở trên, bản sao sở hữu dữ liệu và chế độ xem không sở hữu dữ liệu, nhưng làm cách nào để kiểm tra điều này?
Mỗi mảng NumPy có thuộc tính cơ sở trả về None nếu mảng đó sở hữu dữ liệu.
Mặt khác, thuộc tính cơ sở đề cập đến đối tượng ban đầu.

In [4]:
# Print the value of the base attribute to check if an array owns it's data or not:
# In giá trị của thuộc tính cơ sở để kiểm tra xem một mảng có sở hữu dữ liệu của nó hay không:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


The copy returns None
The view returns the original array
Bản sao trả về None
Chế độ xem trả về mảng ban đầu