Reshaping arrays
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.
Định hình lại mảng
Định hình lại có nghĩa là thay đổi hình dạng của một mảng.
Hình dạng của mảng là số phần tử trong mỗi chiều.
Bằng cách định hình lại, chúng ta có thể thêm hoặc bớt các kích thước hoặc thay đổi số phần tử trong mỗi kích thước.

Reshape From 1-D to 2-D
Định hình lại từ 1-D thành 2-D

In [2]:
'''Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:'''
''' Chuyển đổi mảng 1-D sau đây với 12 phần tử thành mảng 2-D.

Chiều ngoài cùng sẽ có 4 mảng, mỗi mảng có 3 phần tử: '''
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshape From 1-D to 3-D
Định hình lại từ 1-D thành 3-D

In [3]:
''' Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:'''
''' Chuyển đổi mảng 1-D sau đây với 12 phần tử thành mảng 3-D.

Chiều ngoài cùng sẽ có 2 mảng gồm 3 mảng, mỗi mảng có 2 phần tử: '''
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.
We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.
Chúng ta có thể định hình lại thành bất kỳ hình dạng nào không?
Có, miễn là các phần tử cần thiết để định hình lại đều bằng nhau ở cả hai hình.
Chúng ta có thể định hình lại mảng 1D 8 phần tử thành 4 phần tử trong mảng 2D 2 hàng nhưng chúng ta không thể định hình lại nó thành mảng 2D 3 phần tử 3 hàng vì điều đó sẽ yêu cầu 3x3 = 9 phần tử.

In [4]:
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):
# Hãy thử chuyển đổi mảng 1D có 8 phần tử thành mảng 2D có 3 phần tử ở mỗi chiều (sẽ báo lỗi):
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

Returns Copy or View?
Trả về Bản sao hoặc Xem?

In [5]:
# Check if the returned array is a copy or a view:
# Kiểm tra xem mảng trả về là bản sao hay dạng xem:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


The example above returns the original array, so it is a view.
Ví dụ trên trả về mảng ban đầu, vì vậy nó là một dạng xem.

Unknown Dimension
You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.
Thứ nguyên không xác định
Bạn được phép có một thứ nguyên "không xác định".
Có nghĩa là bạn không phải chỉ định số chính xác cho một trong các kích thước trong phương pháp định hình lại.
Chuyển -1 giá trị này và NumPy sẽ tính con số này cho bạn.

In [6]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:
# Chuyển đổi mảng 1D có 8 phần tử thành mảng 3D có phần tử 2x2:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Note: We can not pass -1 to more than one dimension.
Lưu ý: Chúng ta không thể chuyển -1sang nhiều chiều.

Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.
Làm phẳng các mảng
Làm phẳng mảng có nghĩa là chuyển đổi một mảng nhiều chiều thành mảng 1D.
Chúng ta có thể sử dụng reshape(-1)để làm điều này.

In [7]:
# Convert the array into a 1D array:
# Chuyển đổi mảng thành mảng 1D:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.
Lưu ý: Có rất nhiều hàm để thay đổi hình dạng của mảng trong numpy flattenvà ravelcũng để sắp xếp lại các phần tử rot90, flip, fliplr, flipudv.v. Những hàm này nằm trong phần Trung cấp đến Nâng cao của numpy.