Iterating Arrays
Iterating means going through elements one by one.
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
If we iterate on a 1-D array it will go through each element one by one.
Lặp lại mảng
Lặp lại có nghĩa là duyệt qua từng phần tử một.
Khi xử lý mảng đa chiều một cách gọn gàng, chúng ta có thể thực hiện việc này bằng cách sử dụng vòng lặp for cơ bản của python.
Nếu chúng ta lặp trên mảng 1-D, nó sẽ đi qua từng phần tử một.

In [1]:
# Iterate on the elements of the following 1-D array:
# Lặp lại các phần tử của mảng 1-D sau:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


Iterating 2-D Arrays
In a 2-D array it will go through all the rows.
Lặp lại mảng 2-D
Trong mảng 2-D, nó sẽ đi qua tất cả các hàng.

In [2]:
# Iterate on the elements of the following 2-D array:
# Lặp lại các phần tử của mảng 2-D sau:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


If we iterate on a n-D array it will go through n-1th dimension one by one.
Nếu chúng ta lặp lại trên một mảng n-D, nó sẽ đi qua từng chiều thứ n-1.

To return the actual values, the scalars, we have to iterate the arrays in each dimension.
Để trả về các giá trị thực tế, các giá trị vô hướng, chúng ta phải lặp lại các mảng theo từng chiều.

In [3]:
# Iterate on each scalar element of the 2-D array:
# Lặp lại từng phần tử vô hướng của mảng 2-D:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.
Lặp lại mảng 3-D
Trong mảng 3-D, nó sẽ đi qua tất cả các mảng 2-D.

In [4]:
# Iterate on the elements of the following 3-D array:
# Lặp lại các phần tử của mảng 3-D sau:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.
Để trả về các giá trị thực tế, các giá trị vô hướng, chúng ta phải lặp lại các mảng theo từng chiều.

In [5]:
# Iterate down to the scalars:
# Lặp lại các đại lượng vô hướng:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.
Lặp lại mảng bằng nditer()
Hàm nditer() là một hàm trợ giúp có thể được sử dụng từ các bước lặp rất cơ bản đến rất nâng cao. Nó giải quyết một số vấn đề cơ bản mà chúng ta gặp phải trong quá trình lặp lại, hãy xem qua nó bằng các ví dụ.

Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.
Lặp lại trên mỗi phần tử vô hướng
Trong các vòng lặp for cơ bản, lặp qua từng vô hướng của một mảng chúng ta cần sử dụng n vòng lặp for, điều này có thể khó viết đối với các mảng có số chiều rất cao.

In [6]:
# Iterate through the following 3-D array:
# Lặp lại qua mảng 3-D sau:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].
Lặp lại mảng với các kiểu dữ liệu khác nhau
Chúng ta có thể sử dụng đối số op_dtypes và truyền cho nó kiểu dữ liệu dự kiến ​​để thay đổi kiểu dữ liệu của các phần tử trong khi lặp.
NumPy không thay đổi kiểu dữ liệu của phần tử tại chỗ (trong đó phần tử nằm trong mảng) nên nó cần một số không gian khác để thực hiện hành động này, không gian thừa đó được gọi là bộ đệm và để kích hoạt nó, nditer() chúng tôi chuyển flags=['buffered'].

In [7]:
# Iterate through the array as a string:
# Lặp lại mảng dưới dạng một chuỗi:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


Iterating With Different Step Size
We can use filtering and followed by iteration.
Lặp lại với kích thước bước khác nhau
Chúng ta có thể sử dụng tính năng lọc và theo sau là phép lặp.

In [8]:
# Iterate through every scalar element of the 2D array skipping 1 element:
# Lặp qua mọi phần tử vô hướng của mảng 2D bỏ qua 1 phần tử:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.
Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.
Phép lặp liệt kê sử dụng ndenumerate()
Việc liệt kê có nghĩa là đề cập đến số thứ tự của từng thứ một.
Đôi khi chúng ta yêu cầu chỉ mục tương ứng của phần tử trong khi lặp, phương thức ndenumerate() có thể được sử dụng cho các usecase đó.

In [9]:
# Enumerate on following 1D arrays elements:
# Liệt kê các phần tử mảng 1D sau:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [10]:
# Enumerate on following 2D array's elements:
# Liệt kê các phần tử của mảng 2D sau:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
