Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.
Tham gia mảng NumPy
Nối có nghĩa là đặt nội dung của hai hoặc nhiều mảng vào một mảng duy nhất.
Trong SQL, chúng ta nối các bảng dựa trên một khóa, trong khi ở NumPy, chúng ta nối các mảng theo trục.
Chúng ta chuyển một chuỗi các mảng mà chúng ta muốn nối vào concatenate() hàm, cùng với trục. Nếu trục không được truyền rõ ràng thì nó được lấy bằng 0.

In [1]:
# Join two arrays
# Nối hai mảng
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [2]:
# Join two 2-D arrays along rows (axis=1):
# Nối hai mảng 2-D dọc theo hàng (trục=1):
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.
Nối các mảng bằng hàm ngăn xếp
Xếp chồng cũng giống như ghép nối, điểm khác biệt duy nhất là việc xếp chồng được thực hiện dọc theo một trục mới.
Chúng ta có thể ghép hai mảng 1-D dọc theo trục thứ hai, điều này sẽ dẫn đến việc đặt chúng chồng lên nhau, tức là. xếp chồng.
Chúng ta chuyển một chuỗi các mảng mà chúng ta muốn nối vào phương stack() thức cùng với trục. Nếu trục không được thông qua một cách rõ ràng thì nó được coi là 0.

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.
Xếp chồng dọc theo hàng
NumPy cung cấp chức năng trợ giúp: hstack() xếp chồng dọc theo các hàng.

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.
Xếp chồng dọc theo cột
NumPy cung cấp chức năng trợ giúp: vstack()  xếp chồng dọc theo các cột.

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
Xếp chồng theo chiều cao (chiều sâu)
NumPy cung cấp chức năng trợ giúp: dstack() xếp chồng theo chiều cao, tương đương với chiều sâu.

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
