Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method.
Tìm kiếm mảng
Bạn có thể tìm kiếm một giá trị nhất định trong mảng và trả về các chỉ mục phù hợp.
Để tìm kiếm một mảng, hãy sử dụng where() phương thức này.

In [1]:
# Find the indexes where the value is 4:
# Tìm các chỉ mục có giá trị là 4:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
The example above will return a tuple: (array([3, 5, 6],)
Which means that the value 4 is present at index 3, 5, and 6.
Ví dụ trên sẽ trả về một bộ dữ liệu:(array([3, 5, 6],)
Điều đó có nghĩa là giá trị 4 hiện diện ở chỉ số 3, 5 và 6.

In [2]:
# Find the indexes where the values are even:
# Tìm các chỉ mục có giá trị chẵn:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [3]:
# Find the indexes where the values are odd:
# Tìm các chỉ mục có giá trị lẻ:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
Tìm kiếm đã được sắp xếp
Có một phương thức được gọi là searchsorted()thực hiện tìm kiếm nhị phân trong mảng và trả về chỉ mục nơi giá trị được chỉ định sẽ được chèn vào để duy trì thứ tự tìm kiếm.

The searchsorted() method is assumed to be used on sorted arrays.
Phương thức này searchsorted()được cho là được sử dụng trên các mảng được sắp xếp.

In [4]:
# Find the indexes where the value 7 should be inserted:
# Tìm các chỉ mục cần chèn giá trị 7:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


Example explained: The number 7 should be inserted on index 1 to remain the sort order.
The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.
Ví dụ giải thích: Số 7 nên được chèn vào chỉ mục 1 để giữ nguyên thứ tự sắp xếp.
Phương thức bắt đầu tìm kiếm từ bên trái và trả về chỉ mục đầu tiên trong đó số 7 không còn lớn hơn giá trị tiếp theo.

Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.
Tìm kiếm từ phía bên phải
Theo mặc định, chỉ mục bên trái nhất được trả về, nhưng side='right'thay vào đó, chúng ta có thể trả về chỉ mục bên phải nhất.

In [5]:
# Find the indexes where the value 7 should be inserted, starting from the right:
# Tìm các chỉ mục cần chèn giá trị 7, bắt đầu từ bên phải:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


Example explained: The number 7 should be inserted on index 2 to remain the sort order.
The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.
Ví dụ giải thích: Số 7 nên được chèn vào chỉ mục 2 để giữ nguyên thứ tự sắp xếp.
Phương thức bắt đầu tìm kiếm từ bên phải và trả về chỉ mục đầu tiên trong đó số 7 không còn nhỏ hơn giá trị tiếp theo.

Multiple Values
To search for more than one value, use an array with the specified values.
Nhiều giá trị
Để tìm kiếm nhiều giá trị, hãy sử dụng một mảng có các giá trị được chỉ định.

In [6]:
# Find the indexes where the values 2, 4, and 6 should be inserted:
# Tìm các chỉ mục trong đó các giá trị 2, 4 và 6 sẽ được chèn vào:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.
Giá trị trả về là một mảng: [1 2 3] chứa ba chỉ mục trong đó 2, 4, 6 sẽ được chèn vào mảng ban đầu để duy trì thứ tự.