Sorting Arrays
Sorting means putting elements in an ordered sequence.
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
The NumPy ndarray object has a function called sort(), that will sort a specified array.
Sắp xếp mảng
Sắp xếp có nghĩa là sắp xếp các phần tử theo một trình tự có thứ tự .
Trình tự có thứ tự là bất kỳ trình tự nào có thứ tự tương ứng với các phần tử, như số hoặc chữ cái, tăng dần hoặc giảm dần.
Đối tượng NumPy ndarray có một hàm gọi là sort(), hàm này sẽ sắp xếp một mảng được chỉ định.

In [1]:
# Sort the array:
# Sắp xếp mảng:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


Note: This method returns a copy of the array, leaving the original array unchanged
Lưu ý: Phương thức này trả về một bản sao của mảng, giữ nguyên mảng ban đầu

You can also sort arrays of strings, or any other data type
Bạn cũng có thể sắp xếp các mảng chuỗi hoặc bất kỳ loại dữ liệu nào khác

In [2]:
# Sort the array alphabetically:
# Sắp xếp mảng theo thứ tự bảng chữ cái:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [3]:
# Sort a boolean array:
# Sắp xếp một mảng boolean:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted
Sắp xếp mảng 2 chiều
Nếu bạn sử dụng phương thức sort() trên mảng 2-D, cả hai mảng sẽ được sắp xếp

In [4]:
# Sort a 2-D array:
# Sắp xếp mảng 2 chiều:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
