Working with Graphs
Graphs are an essential data structure.

SciPy provides us with the module scipy.sparse.csgraph for working with such data structur
Làm việc với đồ thị
Đồ thị là một cấu trúc dữ liệu thiết yếu.

SciPy cung cấp cho chúng ta mô-đun scipy.sparse.csgraphđể làm việc với các cấu trúc dữ liệu như vậy.es.

Adjacency Matrix
Adjacency matrix is a nxn matrix where n is the number of elements in a graph.

And the values represents the connection between the elemen
Ma trận kề
Ma trận kề là nxnma trận n chứa số phần tử của đồ thị.

Và các giá trị thể hiện sự kết nối giữa các phần tử.ts.

Connected Components
Find all of the connected components with the connected_components() method
Các thành phần được kết nối
Tìm tất cả các thành phần được kết nối bằng connected_components()phương thức..

In [1]:
import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(connected_components(newarr))

(1, array([0, 0, 0]))


Dijkstra
Use the dijkstra method to find the shortest path in a graph from one element to another.

It takes following argument:

return_predecessors: boolean (True to return whole path of traversal otherwise False).
indices: index of the element to return all paths from that element only.
limit: max weight o
Dijkstra
Sử dụng dijkstraphương pháp này để tìm đường đi ngắn nhất trong biểu đồ từ phần tử này đến phần tử khác.

Phải mất các đối số sa:

return_predecessors: boolean (Đúng để trả về toàn bộ đường đi nếu không là Sai).
chỉ mục: chỉ mục của phần tử để chỉ trả về tất cả các đường dẫn từ phần tử đó.
giới hạn: trọng lượng tối đa của đường dẫn.f path.

In [2]:
# Find the shortest path from element 1 to 2:
# Tìm đường đi ngắn nhất từ ​​phần tử 1 đến phần tử 2:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(dijkstra(newarr, return_predecessors=True, indices=0))

(array([0., 1., 2.]), array([-9999,     0,     0]))


Floyd Warshall
Use the floyd_warshall() method to find shortest path between all pairs of elements
Floyd Warshall
Sử dụng floyd_warshall()phương pháp tìm đường đi ngắn nhất giữa tất cả các cặp phần tử..

In [3]:
# Find the shortest path between all pairs of elements:
# Tìm đường đi ngắn nhất giữa tất cả các cặp phần tử:
import numpy as np
from scipy.sparse.csgraph import floyd_warshall
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


Bellman Ford
The bellman_ford() method can also find the shortest path between all pairs of elements, but this method can handle negative weights as well
Bellman Ford
Phương thức này bellman_ford()cũng có thể tìm ra đường đi ngắn nhất giữa tất cả các cặp phần tử, nhưng phương pháp này cũng có thể xử lý các trọng số âm..

In [4]:
# Find shortest path from element 1 to 2 with given graph with a negative weight:
# Tìm đường đi ngắn nhất từ ​​phần tử 1 đến phần tử 2 với đồ thị đã cho có trọng số âm:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=0))

(array([ 0., -1.,  2.]), array([-9999,     0,     0]))


Depth First Order
The depth_first_order() method returns a depth first traversal from a node.

This function takes following argument:

the graph.
the starting element to traverse graph
Độ sâu thứ tự đầu tiên
Phương depth_first_order()thức trả về độ sâu truyền tải đầu tiên từ một nút.

Hàm này có các đối số sa:

đồ thị.
phần tử bắt đầu để duyệt đồ thị từ đó. from.

In [5]:
# Traverse the graph depth first for given adjacency matrix:
# Duyệt qua độ sâu của biểu đồ trước cho ma trận kề đã cho:
import numpy as np
from scipy.sparse.csgraph import depth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(depth_first_order(newarr, 1))

(array([1, 0, 3, 2]), array([    1, -9999,     1,     0]))


Breadth First Order
The breadth_first_order() method returns a breadth first traversal from a node.

This function takes following argument:

the graph.
the starting element to traverse graph
Thứ tự đầu tiên theo chiều rộng
Phương thức này breadth_first_order()trả về lần truyền tải đầu tiên theo chiều rộng từ một nút.

Hàm này có các đối số sa:

đồ thị.
phần tử bắt đầu để duyệt đồ thị từ đó. from.

In [6]:
# Traverse the graph breadth first for given adjacency matrix:
# Duyệt qua chiều rộng đồ thị trước cho ma trận kề đã cho:
import numpy as np
from scipy.sparse.csgraph import breadth_first_order
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 0, 1],
  [1, 1, 1, 1],
  [2, 1, 1, 0],
  [0, 1, 0, 1]
])

newarr = csr_matrix(arr)

print(breadth_first_order(newarr, 1))

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))
