Trigonometric Functions
NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values
Hàm lượng giác
NumPy cung cấp ufuncs sin,và cos vàận tan nhận ()các giá trị tính bằng radian và tạo ra các giá trị sin, cos và tan tương ứ..

In [1]:
# Find sine value of PI/2:
# Tìm giá trị sin của PI/2:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [2]:
# Find sine values for all of the values in arr:
# Tìm giá trị sin cho tất cả các giá trị trong mảng:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


Convert Degrees Into Radians
By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy
Chuyển đổi độ thành radian
Theo mặc định, tất cả các hàm lượng giác đều lấy radian làm tham số nhưng chúng ta có thể chuyển đổi radian sang độ và ngược lại trong Num..

Note: radians values are pi/180 * degree_values
Lưu ý: giá trị radian là pi/180 * Degree_values

In [3]:
# Convert all of the values in following array arr to radians:
# Chuyển đổi tất cả các giá trị trong mảng mảng sau sang radian:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


Radians to Degrees
Radian sang Độ

In [4]:
# Convert all of the values in following array arr to degrees:
# Chuyển đổi tất cả các giá trị trong mảng mảng sau sang độ:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


Finding Angles
Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).
NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values geniv
Tìm góc
Tìm các góc từ các giá trị của sin, cos, tan. Ví dụ: sin, cos và tan nghịch đảo (arcsin, arccos, arctn.

NumPy cung cấp ufuncs arcs in()và tạo ra các giá trị radian cho các giá trị sin, cos và tan tương ứng đã)en.

In [5]:
# Find the angle of 1.0:
# Tìm góc 1,0:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


Angles of Each Value in Arrays
Góc của mỗi giá trị trong mảng

In [6]:
# Find the angle for all of the sine values in the array
# Tìm góc cho tất cả các giá trị sin trong mảng
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


Hypotenues
Finding hypotenues using pythagoras theorem in NumPy

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras themeCr
cạnh huyền
Tìm cạnh huyền bằng định lý pythagoras trong NPy.

NumPy cun hàmg cấphyp()hàm lấy các giá trị cơ sở và vuông góc rồi tạo ra các cạnh huyền dựa trên định lý pythas.em.

In [7]:
# Find the hypotenues for 4 base and 3 perpendicular:
# Tìm các cạnh huyền cho 4 đáy và 3 đường vuông góc:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
