What is a Set
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operatio
Bộ là gì
Tập hợp trong toán học là tập hợp các phần tử duy nhất.

Các bộ được sử dụng cho các phép toán liên quan đến các phép toán giao nhau, hợp và sai thường xuy.ns.



Create Sets in NumPy
We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays
Tạo bộ trong NumPy
Chúng ta có thể sử dụng phương pháp của NumPy unique()để tìm các phần tử duy nhất từ ​​bất kỳ mảng nào. Ví dụ: tạo một mảng tập hợp, nhưng hãy nhớ rằng mảng tập hợp chỉ nên là mảng 1-D..

In [1]:
# Convert following array with repeated elements to a set:
# Chuyển đổi mảng sau với các phần tử lặp lại thành một tập hợp:
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


Finding Union
To find the unique values of two arrays, use the union1d() method
Tìm Liên Minh
Để tìm các giá trị duy nhất của hai mảng, hãy sử dụng phươn thức  union1d( ...

In [2]:
# Find union of the following two set arrays:
# Tìm hợp của hai tập hợp sau:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


Finding Intersection
To find only the values that are present in both arrays, use the intersect1d() method
Tìm giao lộ
Để chỉ tìm các giá trị có trong cả hai mảng, hãy sử dụng intersect1d()phương thức này..

In [3]:
# Find intersection of the following two set arrays:
# Tìm giao điểm của hai tập hợp sau:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.
Lưu ý: phương thức này intersect1d()lấy một đối số tùy chọn assume_unique, nếu được đặt thành True thì có thể tăng tốc độ tính toán. Nó phải luôn được đặt thành True khi xử lý các tập hợp.

Finding Difference
To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method
Tìm sự khác biệt
Để chỉ tìm các giá trị trong tập đầu tiên KHÔNG có trong tập giây, hãy sử dụng phương setdiff1d()thức..

In [4]:
# Find the difference of the set1 from set2:
# Tìm sự khác biệt của set1 so với set2:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


Note: the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.
Lưu ý: phương thức này setdiff1d() lấy một đối số tùy chọn assume_unique, nếu được đặt thành True thì có thể tăng tốc độ tính toán. Nó phải luôn được đặt thành True khi xử lý các tập hợp.

Finding Symmetric Difference
To find only the values that are NOT present in BOTH sets, use the setxor1d() method
Tìm sự khác biệt đối xứng
Để chỉ tìm các giá trị KHÔNG có trong CẢ HAI bộ, hãy sử dụng setxor1d()phương thức này..

In [5]:
# Find the symmetric difference of the set1 and set2:
# Tìm sự khác biệt đối xứng của set1 và set2:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


Note: the setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.
Lưu ý: phương thức này setxor1d() lấy một đối số tùy chọn assume_unique, nếu được đặt thành True thì có thể tăng tốc độ tính toán. Nó phải luôn được đặt thành True khi xử lý các tập hợp.