In [1]:
import numpy as np

In [2]:
np.array([1, 6, 9, 12])

array([ 1,  6,  9, 12])

In [3]:
# Vì mảng NumPy bắt buộc phải cùng kiểu dữ liệu, nên nếu khác thì nó sẽ cố ép sao cho toàn bộ mảng cùng kiểu, chẳng hạn như:
np.array([6.99, 1, 2, 3])

array([6.99, 1.  , 2.  , 3.  ])

In [4]:
# Ta thấy toàn bộ kiểu dữ liệu đã chuyển sang số thực để đồng bộ. Ngoài ra ta có thể khai báo trước kiểu dữ liệu của mảng:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
# Quan trọng nhất, mảng NumPy có thể đa chiều, không giống như List chỉ có thể lưu trữ dữ liệu 1 chiều, ví dụ:
np.array([range(i, i + 5) for i in [1, 2, 3, 4]])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [6]:
# Tạo mảng có 5 phần tử mà mọi giá trị đều bằng 0
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [7]:
# Tạo mảng đa chiều kích thước 5x5 mà mọi giá trị đều = 1
np.ones((5, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Tạo mảng đa chiều kích thước 3x3 mà mọi giá trị đều = 100
np.full((3, 3), 100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [9]:
# Dùng np.arange để tạo mảng tuyến tính, bắt đầu bằng 0, kết thúc bằng 10, bước nhảy là 2:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
# Dùng np.linspace để tạo mảng tuyến tính với 5 phần tử và các phần tử có giá trị từ 0 đến 2:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
# Tạo mảng 3x3 phân bố đều với các phần tử có giá trị ngẫu nhiên giữa 0 và 1:
np.random.random((3, 3))

array([[0.26833108, 0.07566853, 0.06990838],
       [0.35291017, 0.73652744, 0.32619884],
       [0.42762277, 0.02661965, 0.42233729]])

In [13]:
# Tạo một mảng 3x3 với các phần tử ngẫu nhiên được phân phối chuẩn với giá trị trung bình là 0 và độ lệch chuẩn 1
np.random.normal(0, 1, (3, 3))

array([[-0.97797963,  0.08840746, -0.49095441],
       [ 1.19069891, -0.5319817 ,  1.46583632],
       [ 2.3170275 ,  1.058686  ,  0.67880564]])

In [14]:
# Tạo một mảng 3x3 các số nguyên ngẫu nhiên trong khoảng [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 9, 0],
       [9, 6, 5],
       [6, 5, 6]])

In [15]:
# Tạo ma trận đơn vị kích thước 3x3:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Tạo mảng rỗng gồm 5 phần tử, giá trị của 5 phần tử này có thể là bất cứ giá trị nào đã lưu trên bộ nhớ trước đó:
np.empty(5)

array([0. , 0.5, 1. , 1.5, 2. ])