1. Thuộc tính mảng NumPy
Trước khi đi đến các phần xử lý mảng, ta sẽ tìm hiểu về các thuộc tính mảng NumPy trước. Chúng ta sẽ lần lượt tạo 3 mảng:

In [19]:
import numpy as np
a1 = np.random.randint(10, size=5) # Mảng 1 chiều
a2 = np.random.randint(10, size=(3, 4)) # Mảng 2 chiều
a3 = np.random.randint(10, size=(3, 4, 5)) # Mảng 3 chiều
a4 = np.random.randint(10, size=(2, 3, 5, 8)) # Mảng 3 chiều
print("a1", a1)
print("a2", a2)
print("a3", a3)
print("a4", a4)

a1 [1 3 5 9 3]
a2 [[7 7 5 9]
 [7 6 6 7]
 [8 2 6 0]]
a3 [[[1 7 5 4 7]
  [5 5 3 9 4]
  [4 9 1 7 0]
  [8 9 3 3 3]]

 [[5 4 4 3 1]
  [7 2 4 2 0]
  [4 7 7 2 2]
  [2 5 3 9 6]]

 [[8 6 1 4 0]
  [8 3 3 6 3]
  [4 5 9 4 9]
  [5 1 1 9 5]]]
a4 [[[[4 4 4 8 4 1 9 9]
   [9 0 8 9 7 4 9 2]
   [1 6 8 5 3 1 6 5]
   [8 0 9 6 3 8 3 3]
   [2 0 3 4 6 6 4 3]]

  [[4 2 4 1 5 6 2 9]
   [2 4 8 6 7 8 9 6]
   [4 0 0 4 0 6 4 5]
   [0 1 4 9 8 9 7 7]
   [1 7 8 2 8 2 4 4]]

  [[3 5 2 0 2 0 7 0]
   [6 2 3 2 8 3 5 4]
   [2 3 9 8 4 5 6 4]
   [6 0 7 3 5 9 2 6]
   [6 3 1 2 4 8 2 5]]]


 [[[7 7 3 7 8 7 5 5]
   [7 2 3 0 8 8 7 2]
   [9 3 3 0 5 0 4 6]
   [6 2 7 7 2 8 4 6]
   [1 0 6 0 0 0 5 5]]

  [[0 4 2 2 5 0 2 4]
   [3 7 6 1 7 2 1 2]
   [0 5 7 6 2 5 0 7]
   [8 7 5 7 3 3 5 0]
   [9 6 5 5 8 8 8 0]]

  [[2 0 8 6 9 0 5 5]
   [6 7 6 2 2 6 7 9]
   [8 2 8 9 8 5 2 2]
   [1 6 1 7 8 5 5 5]
   [2 4 0 2 6 1 9 3]]]]


Mỗi mảng sẽ có 3 thuộc tính chính:
ndim: số chiều của mảng
shape: kích thước của từng chiều
size: tổng kích thước của mảng (bằng số lượng phần tử trong mảng)

In [14]:
# Chẳng hạn, ta có thể kiểm tra thuộc tính của mảng a2:
print("a2 ndim: ", a2.ndim)
print("a2 shape: ", a2.shape)
print("a2 size: ", a2.size)
print("a4 ndim: ", a4.ndim)
print("a4 shape: ", a4.shape)
print("a5 shape: ", a5.shape)

a2 ndim:  2
a2 shape:  (3, 4)
a2 size:  12
a4 ndim:  3
a4 shape:  (4, 5, 6)
a5 shape:  (2, 4, 5, 6)


In [4]:
# Một thuộc tính khác mà ta cũng cần quan tâm đó là dtype, thuộc tính này biểu thị kiểu dữ liệu của mảng (ta đã nói về kiểu dữ liệu ở bài 02):
print("a2 dtype: ", a2.dtype)

a2 dtype:  int32


In [5]:
''' Thuộc tính cuối cùng mình muốn đề cập là itemsize (hiển thị kích thước tính bằng byte của mỗi mảng phần tử con) 
và nbytes (hiển thị tổng kích thước tính bằng byte của mảng), 
đây là thuộc tính khá hữu dụng nếu chúng ta muốn quan sát mảng đang chiếm bộ nhớ như thế nào, chẳng hạn: '''
print("itemsize:", a3.itemsize, " bytes")
print("nbytes:", a3.nbytes, " bytes")

itemsize: 4  bytes
nbytes: 240  bytes


2. Array Indexing
Nếu như bạn đã quen thuộc với cách truy cập các phần tử của List trong Python, thì với NumPy cũng khá tương tự.

In [9]:
a1

array([2, 8, 2, 1, 6])

In [8]:
a1[3]

1

In [10]:
a3

array([[[6, 3, 7, 6, 4],
        [6, 3, 0, 9, 5],
        [7, 3, 6, 7, 1],
        [5, 3, 1, 6, 2]],

       [[5, 2, 8, 9, 9],
        [1, 5, 6, 0, 5],
        [1, 2, 7, 5, 5],
        [9, 8, 2, 5, 0]],

       [[7, 8, 1, 8, 1],
        [5, 4, 5, 8, 0],
        [5, 0, 6, 5, 6],
        [8, 8, 8, 0, 2]]])