What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.
Số ngẫu nhiên là gì?
Số ngẫu nhiên KHÔNG có nghĩa là một số khác nhau mỗi lần. Ngẫu nhiên có nghĩa là cái gì đó không thể dự đoán được một cách logic.

Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.
If there is a program to generate random number it can be predicted, thus it is not truly random.
Random numbers generated through a generation algorithm are called pseudo random.
Can we make truly random numbers?
Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.
We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).
In this tutorial we will be using pseudo random numbers.
Giả ngẫu nhiên và ngẫu nhiên thực sự.
Máy tính hoạt động trên các chương trình và chương trình là tập hợp các hướng dẫn dứt khoát. Vì vậy, điều đó có nghĩa là phải có một số thuật toán để tạo ra một số ngẫu nhiên.
Nếu có một chương trình tạo số ngẫu nhiên thì nó có thể được dự đoán trước, do đó nó không thực sự ngẫu nhiên.
Các số ngẫu nhiên được tạo thông qua thuật toán tạo được gọi là giả ngẫu nhiên .
Chúng ta có thể tạo ra những con số thực sự ngẫu nhiên không?
Đúng. Để tạo một số thực sự ngẫu nhiên trên máy tính của chúng tôi, chúng tôi cần lấy dữ liệu ngẫu nhiên từ một số nguồn bên ngoài. Nguồn bên ngoài này nói chung là các thao tác gõ phím, di chuyển chuột, dữ liệu trên mạng, v.v.
Chúng ta không cần các số thực sự ngẫu nhiên, trừ khi nó liên quan đến bảo mật (ví dụ: khóa mã hóa) hoặc cơ sở ứng dụng là tính ngẫu nhiên (ví dụ: Bánh xe roulette kỹ thuật số).
Trong hướng dẫn này, chúng tôi sẽ sử dụng các số giả ngẫu nhiên.

Generate Random Number
NumPy offers the random module to work with random numbers.
Tạo số ngẫu nhiên
NumPy cung cấp random mô-đun để làm việc với các số ngẫu nhiên.

In [1]:
# Generate a random integer from 0 to 100:
# Tạo một số nguyên ngẫu nhiên từ 0 đến 100:
from numpy import random

x = random.randint(100)

print(x)

54


Generate Random Float
The random module's rand() method returns a random float between 0 and 1.
Tạo số thả nổi ngẫu nhiên
Phương thức của mô-đun ngẫu nhiên rand() trả về một số float ngẫu nhiên trong khoảng từ 0 đến 1.

In [3]:
# Generate a random float from 0 to 1:
# Tạo một float ngẫu nhiên từ 0 đến 1:
from numpy import random

x = random.rand()

print(x)

0.699930066421852


Generate Random Array
In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.
Tạo mảng ngẫu nhiên
Trong NumPy, chúng tôi làm việc với mảng và bạn có thể sử dụng hai phương thức từ các ví dụ trên để tạo các mảng ngẫu nhiên.

Integers
The randint() method takes a size parameter where you can specify the shape of an array.
số nguyên
Phương thức này randint() lấy một size tham số trong đó bạn có thể chỉ định hình dạng của một mảng.

In [5]:
# Generate a 1-D array containing 5 random integers from 0 to 100:
# Tạo mảng 1-D chứa 5 số nguyên ngẫu nhiên từ 0 đến 100:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[15 96 52  0  4]


In [6]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
# Tạo mảng 2-D có 3 hàng, mỗi hàng chứa 5 số nguyên ngẫu nhiên từ 0 đến 100:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[54 50 77 90 11]
 [43 87 91 34 63]
 [37 70 35 23 14]]


Floats
The rand() method also allows you to specify the shape of the array.
Phao
Phương thức này rand() cũng cho phép bạn chỉ định hình dạng của mảng.

In [7]:
# Generate a 1-D array containing 5 random floats:
# Tạo mảng 1-D chứa 5 số float ngẫu nhiên:
from numpy import random

x = random.rand(5)

print(x)

[0.88019886 0.62431668 0.55000025 0.12188767 0.30791572]


In [8]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
# Tạo mảng 2-D có 3 hàng, mỗi hàng chứa 5 số ngẫu nhiên:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.15511102 0.6379079  0.90622137 0.5204201  0.85443972]
 [0.99390991 0.84986886 0.36530041 0.49217637 0.21877368]
 [0.046962   0.67053754 0.88893821 0.49864091 0.56410717]]


Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.
The choice() method takes an array as a parameter and randomly returns one of the values.
Tạo số ngẫu nhiên từ mảng
Phương pháp này choice() cho phép bạn tạo một giá trị ngẫu nhiên dựa trên một mảng các giá trị.
Phương thức này choice() lấy một mảng làm tham số và trả về ngẫu nhiên một trong các giá trị.

In [9]:
# Return one of the values in an array:
# Trả về một trong các giá trị trong một mảng:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


The choice() method also allows you to return an array of values.
Add a size parameter to specify the shape of the array.
Phương thức này choice()cũng cho phép bạn trả về một mảng giá trị.
Thêm một sizetham số để xác định hình dạng của mảng.

In [10]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
# Tạo mảng 2-D bao gồm các giá trị trong tham số mảng (3, 5, 7 và 9):
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 3 9 7 7]
 [7 9 7 7 3]
 [3 9 9 7 5]]
