What is Data Distribution?
Data Distribution is a list of all possible values, and how often each value occurs.
Such lists are important when working with statistics and data science.
The random module offer methods that returns randomly generated data distributions.
Phân phối dữ liệu là gì?
Phân phối dữ liệu là danh sách tất cả các giá trị có thể có và tần suất xuất hiện của mỗi giá trị.
Danh sách như vậy rất quan trọng khi làm việc với thống kê và khoa học dữ liệu.
Mô-đun ngẫu nhiên cung cấp các phương thức trả về phân phối dữ liệu được tạo ngẫu nhiên.

Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function.
Phân phối ngẫu nhiên
Phân phối ngẫu nhiên là tập hợp các số ngẫu nhiên tuân theo một hàm mật độ xác suất nhất định .

Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.
Hàm mật độ xác suất: Hàm mô tả xác suất liên tục. tức là xác suất của tất cả các giá trị trong một mảng.

We can generate random numbers based on defined probabilities using the choice() method of the random module.
The choice() method allows us to specify the probability for each value.
The probability is set by a number between 0 and 1, where 0 means that the value will never occur and 1 means that the value will always occur.
Chúng ta có thể tạo các số ngẫu nhiên dựa trên xác suất xác định bằng choice()phương pháp của randommô-đun.
Phương pháp này choice() cho phép chúng ta xác định xác suất cho từng giá trị.
Xác suất được đặt bởi một số từ 0 đến 1, trong đó 0 có nghĩa là giá trị sẽ không bao giờ xuất hiện và 1 có nghĩa là giá trị sẽ luôn xuất hiện.

ExampleGet your own Python Server
Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
The probability for the value to be 3 is set to be 0.1
The probability for the value to be 5 is set to be 0.3
The probability for the value to be 7 is set to be 0.6
The probability for the value to be 9 is set to be 0
Tạo mảng 1-D chứa 100 giá trị, trong đó mỗi giá trị phải là 3, 5, 7 hoặc 9.
Xác suất để giá trị là 3 được đặt là 0,1
Xác suất để giá trị là 5 được đặt là 0,3
Xác suất để giá trị là 7 được đặt là 0,6
Xác suất để giá trị là 9 được đặt là 0

In [1]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 7 7 5 7 5 7 5 3 7 5 7 7 7 7 5 7 7 7 7 5 7 7 7 7 5 7 7 7 7 5 3 7 5 7
 7 5 7 3 7 7 7 7 5 7 7 7 7 7 7 7 7 7 7 5 3 7 5 7 3 7 7 3 7 7 5 7 7 7 7 7 5
 7 7 5 7 7 7 7 5 7 7 7 5 7 7 5 5 7 7 7 7 5 3 5 7 7 5]


The sum of all probability numbers should be 1.
Tổng của tất cả các số xác suất phải là 1.

Even if you run the example above 100 times, the value 9 will never occur.
You can return arrays of any shape and size by specifying the shape in the size parameter.
Ngay cả khi bạn chạy ví dụ trên 100 lần, giá trị 9 sẽ không bao giờ xuất hiện.
Bạn có thể trả về mảng có hình dạng và kích thước bất kỳ bằng cách chỉ định hình dạng trong tham số size.

In [2]:
# Same example as above, but return a 2-D array with 3 rows, each containing 5 values.
# Ví dụ tương tự như trên, nhưng trả về mảng 2-D có 3 hàng, mỗi hàng chứa 5 giá trị.
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 7 5 7 7]
 [5 7 5 5 5]
 [7 7 5 7 7]]
